### PR TITLE
Add Android/iOS build actions & tune example+tests

### PR DESCRIPTION
**Pull request by davidgovea**
Hi @WrathChaos!

Saw that you upgraded the example recently.. nice :+1: 

While working on #29, I had the need to switch the example back to "local file" mode, rather than pulling from npm.
Due to the recent "publish-from-`build/`" structure tweaks you recently made, this took a few more changes than I was originally intending.

So, I took the opportunity to also add native build jobs, rather than only mangle your project :stuck_out_tongue_closed_eyes: 

Changes in this PR:
* The example test wasn't actually running. Fixed the Action.
* Example app uses the live/local code. Required `metro.config.js` and `babel` configuration.
* The package is now deployed from the root (removed `package.json`-copying and `build/` folder nesting)
  * Sorry for this! I don't like to fight with package-owner's structure decisions, but this makes the local approach in `example` much more straightforward.
  * If you'd like to keep the previous structure, I can figure out the required babel/metro requirements to dig into the build folder.
* TypeScript config tweaks: excluding the build/dist directory to avoid existing-file conflicts when running `tsc`, disabling incremental compilation to avoid `.tsbuildconfig` file in the npm archive.

Thanks for reading! Again.. some of this stuff is pretty opinion-driven, so happy to make changes.

### CODE REVIEW

**Comment by WrathChaos** [comment]
@davidgovea Hello again,
Another great approach and great explanation, thank you for awesome work :) 
I really like your work and explanations. 

Actually, I like it. I will approve this PR but unfortunately, I believe that the `build` folder is a necessity for better handling and future dev usage. I know it will take your time to manage that but please dig the logic into the `build` folder.

**Comment by davidgovea** [comment]
@WrathChaos sounds good!

Looking at it again, I think I was misunderstanding the `build` directory. Due to the `cp package.json build/dist/`, I thought the package was being published from the build or dist folder, but it actually doesn't look like that's the case ("main" is still build/dist/Icon.js).

So I guess I pretty much just renamed "build" to "dist".. can definitely change that back.

Is it your intent to publish from build? Or are you aiming for an archive structured like:
* package.json
* README.md
* build/
  * dist/
    * Icon.js
* lib/
  * Icon.tsx

Looks like there are some boilerplate/cruft holdovers in the package too.. mentions of `src/`, etc

**Comment by WrathChaos** [comment]
I do not publish it from build's package.json, actually, it does not even require to copy the package.json inside the build. We can remove it from the command :) The structure looks good to me.

**Comment by WrathChaos** [comment]
@davidgovea Do you have any chance to improve this PR? :)

**Pull request closed without merging**
