### PR TITLE
Pass remaining props to the Icon component

### PR DESCRIPTION
**Pull request by wesleycoder**
We should pass additional props down to the underlying component to enable better integration with tools and better approach for testing.

### CODE REVIEW

**Comment by WrathChaos** [comment]
Hello @wesleycoder,
Thank you so much for this contribution. I totally agree with you but before merge your PR. I want to discuss the 'name' prop. Other props rather than 'name' and 'type' totally should be dynamic as you said for better integration and testing but in my opinion name and type should be specific for the user to use it well. What do you think about it ? If you agree, let's change with 'name' and 'type' props and I will merge it :) 

Also, I will try to make it better libs with dynamic props :) Thank you again

**Comment by wesleycoder** [comment]
I sure agree with this and I'm making these changes right now.

I'm also adding `prop-types` to the peerDependencies and `propTypes` property to the component in order to help with the usage documentation on editors and other tools.

**Comment by WrathChaos** [comment]
Thank you so much :O waiting for you :)

**Comment by WrathChaos** [comment]
@wesleycoder,
The newer version is alive :) 

### [Release: 0.0.4](https://github.com/WrathChaos/react-native-dynamic-vector-icons/releases/tag/0.0.4)

**Pull request merged**
